version: 1
disable_existing_loggers: false

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: color_fmt
    # args: (sys.stdout,)
  fileHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: fmt
    filename: logs/ui_clock.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
    # args: ('logs/ui_clock.log','a',10000000,10,)
  errorHandler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: fmt
    filename: logs/errors.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
formatters:
  fmt: 
    format: '[%(asctime)s][%(levelname)s][%(name)s] - %(message)s - (%(filename)s:%(funcName)s:%(lineno)d)'
    datefmt:
  color_fmt:
    class: utils.ColoredFormatter
    format: '[%(asctime)s][%(levelname)s][%(name)s] - %(message)s - (%(filename)s:%(funcName)s:%(lineno)d)'
    datefmt:

# loggers:
#   main:
#     level: DEBUG
#     qualname: main
#     handlers: [fileHandler]
#   thread:
#     level: DEBUG
#     qualname: thread
#     handlers: [fileHandler]

root:
  level: DEBUG
  handlers: [consoleHandler,fileHandler]

